version: '3.8'

services:
  backend:
    build: 
      context: ./chatbot_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./chatbot_backend/.env
    environment:
      - ENVIRONMENT=development
    volumes:
      - ./chatbot_backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  chroma_data: 