services:
  backend:
    build: 
      context: ./chatbot_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./chatbot_backend/.env
    environment:
      - ENVIRONMENT=production
      # In development, use the host IP. In production, this will be overridden
      - PUBLIC_URL=http://192.168.0.62:8000
      - ALLOWED_ORIGINS=http://192.168.0.62,http://192.168.0.62:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  frontend:
    build:
      context: ./cv_flutter_app
      dockerfile: Dockerfile
      args:
        # In development, use the host IP. In Azure, this will be the backend's FQDN
        - BACKEND_URL=http://192.168.0.62:8000
    ports:
      - "80:80"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  chroma_data: 